version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # Порт для S3 совместимого API
      - "9001:9001"   # Порт для консоли управления MinIO
    volumes:
      - ./minio_data:/data    # Хранение данных на хосте
    command: server /data --console-address ":9001"
